/* ===== ITEM POOL (임시 이모티콘) ===== */
const I = {
  글러브:{n:"장갑",img:"assets/goods/glove.png"},
  목도리:{n:"목도리",img:"assets/goods/muffler.png"},
  털모자:{n:"털모자",img:"assets/goods/fur_hat.png"},
  수영복:{n:"수영복",img:"assets/goods/swimsuit.png"},
  부채:{n:"부채",img:"assets/goods/folding_fan.png"},
  선풍기:{n:"선풍기",img:"assets/goods/electric_fan.png"},
  난로:{n:"난로",img:"assets/goods/stove.png"},
  수박:{n:"수박",img:"assets/goods/watermelon.png"},
  우산:{n:"우산",img:"assets/goods/umbrella.png"},
  장화:{n:"장화",img:"assets/goods/boots.png"},
  우비:{n:"우비",img:"assets/goods/raincoat.png"},
  선글라스:{n:"선글라스",img:"assets/goods/sunglass.png"},
  장바구니:{n:"장바구니",img:"assets/goods/basket.png"},
  지갑:{n:"지갑",img:"assets/goods/wallet.png"},
  등산화:{n:"등산화",img:"assets/goods/hiking_boots.png"},
  물통:{n:"물통",img:"assets/goods/bucket.png"},
  모자:{n:"모자",img:"assets/goods/cap.png"},
  책가방:{n:"책가방",img:"assets/goods/backpack.png"},
  공책:{n:"공책",img:"assets/goods/textbook.png"},
  연필:{n:"연필",img:"assets/goods/pencil.png"},
  진료카드:{n:"진료카드",img:"assets/goods/patient_card.png"},
  마스크:{n:"마스크",img:"assets/goods/mask.png"},
  약:{n:"약",img:"assets/goods/medicine.png"},
  칫솔:{n:"칫솔",img:"assets/goods/toothbrush.png"},
  치약:{n:"치약",img:"assets/goods/toothpaste.png"},
  수건:{n:"수건",img:"assets/goods/towel.png"},
  커피:{n:"커피",img:"assets/goods/coffee.png"},
  "커피 잔":{n:"커피 잔",img:"assets/goods/coffee_mug.png"},
  "커피 포트":{n:"커피 포트",img:"assets/goods/coffee_pot.png"},
  라면:{n:"라면",img:"assets/goods/ramen.png"},
  달걀:{n:"달걀",img:"assets/goods/egg.png"},
  컵:{n:"컵",img:"assets/goods/cup.png"},
  숟가락:{n:"숟가락",img:"assets/goods/spoon.png"},
  젓가락:{n:"젓가락",img:"assets/goods/chopsticks.png"},
  밥그릇:{n:"밥그릇",img:"assets/goods/bowl.png"},
  국그릇:{n:"국그릇",img:"assets/goods/soup_bowl.png"},
  프라이팬:{n:"프라이팬",img:"assets/goods/pan.png"},
  냄비:{n:"냄비",img:"assets/goods/pot_new.png"},
  베개:{n:"베개",img:"assets/goods/pillow.png"},
  이불:{n:"이불",img:"assets/goods/blanket.png"},
  빗자루:{n:"빗자루",img:"assets/goods/broom.png"},
  걸레:{n:"걸레",img:"assets/goods/rag.png"},
  손전등:{n:"손전등",img:"assets/goods/flashlight.png"},
  소화기:{n:"소화기",img:"assets/goods/fire_extinguisher.png"},
  튜브:{n:"튜브",img:"assets/goods/tube.png"},
  비누:{n:"비누",img:"assets/goods/soap.png"},
  샴푸:{n:"샴푸",img:"assets/goods/shampoo.png"},
  쓰레기통:{n:"쓰레기통",img:"assets/goods/trash_can.png"},
  쓰레받기:{n:"쓰레받기",img:"assets/goods/dustpan.png"},
  "주방용 세제":{n:"주방용 세제",img:"assets/goods/dish_soap.png"},
  고무장갑:{n:"고무장갑",img:"assets/goods/rubber_gloves.png"},
  수세미:{n:"수세미",img:"assets/goods/sponge.png"},
  삽:{n:"삽",img:"assets/goods/shovel.png"},
  씨앗:{n:"씨앗",img:"assets/goods/seeds.png"},
  쌀:{n:"쌀",img:"assets/goods/rice.png"},
  교통카드:{n:"교통카드",img:"assets/goods/transit_card.png"},
  노트북:{n:"노트북",img:"assets/goods/laptop.png"},
  물뿌리개:{n:"물뿌리개",img:"assets/goods/watering_can.png"},
  휴대폰:{n:"휴대폰",img:"assets/goods/smartphone.png"},
  스마트폰:{n:"스마트폰",img:"assets/goods/smartphone.png"},
  이어폰:{n:"이어폰",img:"assets/goods/earphones.png"},
  운동화:{n:"운동화",img:"assets/goods/sneakers_clean.png"},
  사료:{n:"사료",img:"assets/goods/dog_food.png"},
  "강아지 밥그릇":{n:"강아지 밥그릇",img:"assets/goods/dog_bowl.png"},
  뼈다귀:{n:"뼈다귀",img:"assets/goods/dog_bone.png"},
  현금:{n:"현금",img:"assets/goods/cash.png"},
  성경:{n:"성경책",img:"assets/goods/bible.png"},
  간식:{n:"간식",img:"assets/goods/snack.png"},
  거울:{n:"거울",img:"assets/goods/mirror.png"},
  고철:{n:"고철",img:"assets/goods/scrap_metal.png"},
  "도서관 카드":{n:"도서관 카드",img:"assets/goods/library_card.png"},
  도서관카드:{n:"도서관 카드",img:"assets/goods/library_card.png"},
  건전지:{n:"건전지",img:"assets/goods/battery.png"},
  도장:{n:"도장",img:"assets/goods/stamp.png"},
  도시락:{n:"도시락",img:"assets/goods/lunch_box.png"},
  돗자리:{n:"돗자리",img:"assets/goods/picnic_mat.png"},
  빈병:{n:"빈병",img:"assets/goods/empty_bottle.png"},
  빗:{n:"빗",img:"assets/goods/comb.png"},
  "빨래 바구니":{n:"빨래 바구니",img:"assets/goods/laundry_basket.png"},
  빨래바구니:{n:"빨래 바구니",img:"assets/goods/laundry_basket.png"},
  빨래집게:{n:"빨래집게",img:"assets/goods/clothespin.png"},
  서류봉투:{n:"서류봉투",img:"assets/goods/document_envelope.png"},
  선물:{n:"선물",img:"assets/goods/gift.png"},
  세탁세제:{n:"세탁세제",img:"assets/goods/laundry_detergent.png"},
  손수레:{n:"손수레",img:"assets/goods/handcart.png"},
  우표:{n:"우표",img:"assets/goods/postage_stamp.png"},
  책:{n:"책",img:"assets/goods/book.png"},
  의자:{n:"의자",img:"assets/goods/chair.png"},
  처방전:{n:"처방전",img:"assets/goods/prescription.png"},
  충전기:{n:"충전기",img:"assets/goods/charger.png"},
  택배상자:{n:"택배상자",img:"assets/goods/parcel_box.png"},
  편지봉투:{n:"편지봉투",img:"assets/goods/letter_envelope.png"},
  통장:{n:"통장",img:"assets/goods/bankbook.png"},
  화분:{n:"화분",img:"assets/goods/flowerpot.png"},
  회원증:{n:"회원증",img:"assets/goods/membership_card.png"},
  수영모:{n:"수영모",img:"assets/goods/swim_cap.png"},
  스트레칭밴드:{n:"스트레칭밴드",img:"assets/goods/stretching_band.png"},
  신분증:{n:"신분증",img:"assets/goods/id_card.png"},
  쓰레기봉투:{n:"쓰레기 봉투",img:"assets/goods/trash_bag.png"},
  "쓰레기 봉투":{n:"쓰레기 봉투",img:"assets/goods/trash_bag.png"},
  안경:{n:"안경",img:"assets/goods/glasses.png"},
  우편물:{n:"우편물",img:"assets/goods/mail.png"},
};
const ITEM_HINTS = {
  글러브:"추운 날 손을 따뜻하게 해줘요.",
  목도리:"추운 날 목을 따뜻하게 감싸줘요.",
  털모자:"추운 날 머리를 따뜻하게 덮어줘요.",
  수영복:"물놀이할 때 몸에 맞게 입어요.",
  부채:"더울 때 손으로 흔들어 바람을 만들어요.",
  선풍기:"더울 때 전기로 바람을 내요.",
  난로:"추운 곳을 따뜻하게 데울 때 써요.",
  수박:"더운 날 시원하게 먹기 좋아요.",
  우산:"비를 막아 몸이 젖지 않게 해줘요.",
  장화:"비 오는 날 발이 젖지 않도록 신어요.",
  우비:"비 오는 날 옷 위에 입어 몸을 보호해요.",
  선글라스:"햇빛이 강할 때 눈을 보호해요.",
  장바구니:"장을 본 뒤 물건을 담아 들고 와요.",
  지갑:"돈이나 카드를 넣어 다닐 때 써요.",
  등산화:"산길을 걸을 때 발을 보호해줘요.",
  물통:"밖에서 마실 물을 담아 가요.",
  모자:"햇빛이나 추위에서 머리를 보호해요.",
  책가방:"공부할 물건을 넣어 메고 다녀요.",
  공책:"글씨를 쓰거나 공부 내용을 적어요.",
  연필:"종이에 글씨나 그림을 그릴 때 써요.",
  진료카드:"병원에서 접수할 때 보여줘요.",
  마스크:"입과 코를 가려 위생을 지킬 때 써요.",
  약:"아플 때 정해진 양을 먹어요.",
  칫솔:"이를 깨끗하게 문질러 닦을 때 써요.",
  치약:"이를 닦을 때 묻혀서 써요.",
  수건:"씻은 뒤 물기를 닦을 때 써요.",
  커피:"따뜻한 음료를 만들 때 넣어요.",
  "커피 잔":"따뜻한 음료를 따라 마실 때 써요.",
  "커피 포트":"물을 끓여 따뜻한 음료를 만들 때 써요.",
  라면:"끓여서 한 끼로 먹는 음식이에요.",
  달걀:"음식에 넣어 익혀 먹기 좋아요.",
  컵:"물을 따라 마실 때 써요.",
  숟가락:"밥이나 국을 떠먹을 때 써요.",
  젓가락:"반찬이나 면을 집어 먹을 때 써요.",
  밥그릇:"밥을 담아 식탁에 놓을 때 써요.",
  국그릇:"국물 음식을 담아 식탁에 놓을 때 써요.",
  프라이팬:"음식을 볶거나 부칠 때 써요.",
  냄비:"국물 음식을 끓일 때 써요.",
  베개:"잠잘 때 머리를 편하게 받쳐줘요.",
  이불:"잠잘 때 몸을 덮어 따뜻하게 해줘요.",
  빗자루:"바닥의 먼지를 쓸어 모을 때 써요.",
  걸레:"바닥이나 물건을 닦을 때 써요.",
  손전등:"어두운 곳을 밝힐 때 써요.",
  소화기:"불이 났을 때 초기 진화에 써요.",
  튜브:"물놀이할 때 몸이 뜨도록 도와줘요.",
  비누:"손이나 몸을 씻을 때 문질러 써요.",
  샴푸:"머리를 감을 때 써요.",
  쓰레기통:"버릴 것을 모아 담는 곳이에요.",
  쓰레받기:"쓸어 모은 먼지를 담아 옮겨요.",
  "주방용 세제":"그릇의 기름기와 때를 씻어낼 때 써요.",
  고무장갑:"물일을 할 때 손을 보호해줘요.",
  수세미:"그릇을 문질러 닦을 때 써요.",
  삽:"흙을 파거나 고를 때 써요.",
  씨앗:"밭이나 화분에 심어 자라게 해요.",
  쌀:"밥을 지을 때 필요한 곡식이에요.",
  교통카드:"대중교통을 탈 때 요금을 찍어요.",
  노트북:"문서 작업이나 인터넷을 할 때 써요.",
  물뿌리개:"식물에 물을 줄 때 써요.",
  휴대폰:"밖에서 연락하거나 전화를 할 때 써요.",
  스마트폰:"음악을 틀거나 연락할 때 써요.",
  이어폰:"음악이나 소리를 혼자 들을 때 귀에 꽂아요.",
  운동화:"걷거나 산책할 때 발을 편하게 해줘요.",
  사료:"강아지에게 밥으로 주는 음식이에요.",
  "강아지 밥그릇":"강아지 밥이나 물을 담아줄 때 써요.",
  뼈다귀:"강아지가 씹거나 간식처럼 먹을 수 있어요.",
  현금:"물건값을 내거나 전달할 때 써요.",
  성경:"예배나 교회 모임에서 읽는 책이에요.",
  간식:"출출할 때 간단히 먹을 수 있어요.",
  거울:"얼굴이나 모습을 확인할 때 써요.",
  고철:"고물상에 가져가 팔거나 재활용할 수 있어요.",
  "도서관 카드":"도서관에서 책을 빌릴 때 보여줘요.",
  도서관카드:"도서관에서 책을 빌릴 때 보여줘요.",
  건전지:"전기가 필요한 물건에 넣어 작동시켜요.",
  도장:"서류에 확인 표시를 찍을 때 써요.",
  도시락:"밖에서 먹을 음식을 담아 가요.",
  돗자리:"바닥에 펴서 앉거나 쉴 때 써요.",
  빈병:"다 쓴 병을 모아 재활용하거나 가져가요.",
  빗:"머리카락을 가지런히 빗을 때 써요.",
  "빨래 바구니":"빨랫감을 모아 담을 때 써요.",
  빨래바구니:"빨랫감을 모아 담을 때 써요.",
  빨래집게:"빨래를 널 때 집어 고정해요.",
  서류봉투:"서류를 구겨지지 않게 담아 가요.",
  선물:"누군가에게 마음을 전할 때 준비해요.",
  세탁세제:"옷을 빨 때 때를 씻어내요.",
  손수레:"무거운 물건을 실어 옮길 때 써요.",
  우표:"편지나 우편물을 보낼 때 붙여요.",
  책:"읽거나 빌려 보는 자료예요.",
  의자:"앉아서 쉬거나 통화할 때 써요.",
  처방전:"약국에서 처방받은 약을 받을 때 보여줘요.",
  충전기:"휴대폰 같은 전자기기를 충전할 때 써요.",
  택배상자:"택배 물건을 포장해서 보낼 때 담아요.",
  편지봉투:"편지를 넣어 보낼 때 써요.",
  통장:"은행에서 입출금이나 계좌 업무를 볼 때 써요.",
  화분:"식물을 심고 기를 때 써요.",
  회원증:"복지관이나 모임에서 회원임을 확인할 때 보여줘요.",
  수영모:"수영장에 들어갈 때 머리에 써요.",
  스트레칭밴드:"운동 전에 몸을 풀거나 근력 운동을 할 때 써요.",
  신분증:"본인 확인이 필요할 때 보여줘요.",
  쓰레기봉투:"쓰레기를 담아 버릴 때 써요.",
  "쓰레기 봉투":"쓰레기를 담아 버릴 때 써요.",
  안경:"글씨나 화면을 더 잘 볼 때 써요.",
  우편물:"우체국에서 보내거나 받을 물건이에요.",
};
const it = k => ({k, ...I[k], h: ITEM_HINTS[k]});

/* Render image with name-text fallback for missing/broken images */
function phHtml(i){
  if(i && i.img){
    const safeName = String(i.n||"").replace(/"/g,"&quot;");
    return `<img src="${i.img}" alt="${safeName}" draggable="false" onerror="this.replaceWith(Object.assign(document.createElement('span'),{textContent:'${safeName}',className:'ph-fallback'}))">`;
  }
  return `<span class="ph-fallback">${i ? (i.n||"") : ""}</span>`;
}
